name: 'Open Pull Requests Reporter'
description: 'Slack messages for your PRs'
author: 'Rufat Khaslarov'
inputs:
  repo-token:
    description: 'Token for the repo. Can be passed in using {{ secrets.GITHUB_TOKEN }}'
    required: true
  slack-webhook:
    description: 'Your slack webhook URL. Used to send PR reporter notifications.'
    required: true
  exclude-labels:
    description: 'Comma seperated list of labels to exclude from PR reports'
  stale-pr:
    description: 'Should stale PRs be marked'
    default: 7
runs:
  using: node20
  main: dist/index.js


